export let themes = {
  default: [
    'It is certain',
    'It is decidedly so',
    'Without a doubt',
    'Yes definitely',
    'You may rely on it',
    'As I see it, yes',
    'Most likely',
    'Outlook good',
    'Yes',
    'Signs point to yes',
    'Reply hazy, try again',
    'Ask again later',
    'Better not tell you now',
    'Cannot predict now',
    'Concentrate and ask again',
    'Dont count on it',
    'My reply is no',
    'My sources say no',
    'Outlook not so good',
    'Very doubtful',
  ],
  moira: [
    'Your future is positively bébélicious!',
    "Darling, you're destined for greatness, like one of my more obscure yet critically acclaimed roles.",
    'Ah, the stars align in your favour, much like my wigs in a perfect row.',
    'Expect nothing but the finest, like a vintage Herb Ertlinger fruit wine.',
    'A triumph is on the horizon, dear. Very coup de théâtre!',
    'Success will follow you, just as admirers follow The Crows Have Eyes III: The Crowening.',
    "Fortune favours you, darling, as you navigate life's grand stage with aplomb.",
    'Your prospects are more splendid than my collection of couture!',
    "Oh, dear. Your path seems as foggy as Jocelyn's taste in fashion.",
    'Your future seems shrouded in uncertainty, an enigmatic conundrum.',
    "Brace yourself, it's going to be a bébé bit rough.",
    'Challenges lie ahead, threatening to disrupt your tranquil existence.',
    'The outcome is darker than my most dramatic gothic wig.',
    'Your fortunes are more tangled than one of my elaborate costumes.',
    "The forecast is gloomier than Roland's flannel collection.",
    'Your luck is more elusive than a good cup of café au lait in this town.',
    "The outcome remains uncertain, like David's next career move.",
    "You'll have to wait and see, darling, as one does for a Cabaret revival.",
    "It's a 50/50 chance, much like Roland remembering an appointment.",
  ],
  greg: [
    "Congratulations, you've won the day with an unexpected flourish!",
    'A brilliant outcome awaits you, like a well-executed task.',
    "Your future is as bright as a golden trophy in the Taskmaster's hand.",
    'Success is on your horizon, you magnificent genius!',
    "Prepare for triumph, just as if you'd outsmarted Alex Horne himself.",
    "You're destined for glory, like a perfectly executed final task.",
    'Victory will be yours, you clever rascal.',
    'Fortune favours you, as if the Taskmaster himself approved.',
    'Oh dear, your efforts seem as futile as a failed team task.',
    'Your future looks as grim as a dismal score in a Taskmaster challenge.',
    "Brace yourself, the outcome is as disappointing as Alex Horne's trickery.",
    'Challenges lie ahead, like an impossible task set by the Taskmaster.',
    'Your prospects are as bleak as a zero-point performance.',
    'The forecast is gloomy, akin to an embarrassing task mishap.',
    'Your luck is as elusive as a well-deserved bonus point.',
    'The result is as unsatisfactory as a half-hearted attempt.',
    "It's a 50/50 chance, much like predicting Greg Davies' next sarcastic remark.",
    'Maybe. Maybe not. What do you want from me, a crystal ball?',
    'Ask again later. I’m busy being magnificent.',
    'Could go either way, like a wobbly contestant on a slippery slope.',
  ],
}
